### ISSUE TITLE
HTTPS Certificate

### ISSUE THREAD

**Issue by meltsys** [jbasen/Crestron---Sensibo-Air#1]
Hello,

I tried on a MC3 and I get this message when pulse Initialize : 

`Error Sending Device Command: Crestron.SimplSharp.Net.Https.HttpsException: Peer certificate cannot be authenticated with given CA certificates
   at Crestron.SimplSharp.Net.Https.HttpsClient.ProcessInternalError(HttpsClientResponse response)
   at Crestron.SimplSharp.Net.Https.HttpsClient.d(HttpsClientRequest A_0, Boolean A_1)
   at Crestron.SimplSharp.Net.Https.HttpsClient.TryDispatch(HttpsClientRequest aRequest)
   at Crestron.SimplSharp.Net.Https.HttpsClient.Dispatch(HttpsClientRequest aRequest)
   at Sensibo_Air_Integration.Sensibo_Air.Refresh()
   at Sensibo_Air_Integration.Sensibo_Air.Initialize(String Device_ID, String API_Key, Int16 Default_Target_Temperature, String Default_Temperature_Unit, Int16 Debug)
   at UserModule_SENSIBO_AIR_V1_4.UserModuleClass_SENSIBO_AIR_V1_4.INITIALIZE_OnPush_0(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.o()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)
   at Amib.Threading.SmartThreadPool.p()
`
Any Idea ?

**Comment by jbasen** [comment]
Sorry, because Crestron abandoned doing firmware updates on the MC3 the module won't work on that platform because the module uses https for communications.  It will run on the CP3 and PRO3.
